### ISSUE TITLE
请问为什么 HttpClient 使用了 socket 而不是 curl

### ISSUE THREAD

**Issue by wozzup** [hightman/pspider#5]
我自己测试 curl multi 比 socket 有更好的并行无阻塞的特性，不知道 hightman 大神是出于什么原因选择了 socket 来做 HttpClient?

**Comment by hightman** [comment]
能不依赖的扩展都尽量不依赖，目前 PHP 的 stream 系列也很强大，这样可以完全做到并行、异步连接，结果处理也很方便。

至于所谓的 curl 有更好的xxx特性，目前还没感觉到。不过我这个 HttpClient 有点沉旧了，还有一点不支持 proxy。

**Comment by wozzup** [comment]
哦哦，学习了，多谢 hightman 大神！求推荐一个比 php domdocument 效率更高的dom分析器。。。
